#!/usr/bin/env python3
"""
Setup script for TOTP Approval Gate

Generates TOTP secret and displays QR code for adding to authenticator app.
"""

import base64
import io
import os
import sys
from pathlib import Path

import pyotp
import qrcode


def main():
    config_dir = Path(os.environ.get("CONFIG_DIR", "/config"))
    config_dir.mkdir(parents=True, exist_ok=True)

    env_file = config_dir / ".env"
    issuer = os.environ.get("TOTP_ISSUER", "UnraidDeploy")
    account = os.environ.get("TOTP_ACCOUNT", "deploy@unraid")

    # Check if already set up
    if env_file.exists():
        print("⚠️  Setup already complete!")
        print(f"   Config: {env_file}")
        print()
        print("To reset, delete the config and run setup again:")
        print(f"   rm {env_file}")
        print()

        # Show existing QR code
        existing = env_file.read_text()
        for line in existing.split("\n"):
            if line.startswith("TOTP_SECRET="):
                secret = line.split("=", 1)[1].strip()
                show_qr(secret, issuer, account)
                break
        return

    # Generate new secret
    secret = pyotp.random_base32()
    totp = pyotp.TOTP(secret)

    # Save to .env file
    env_content = f"""# TOTP Approval Gate Configuration
# Generated by setup.py - DO NOT COMMIT THIS FILE

TOTP_SECRET={secret}
TOTP_ISSUER={issuer}

# =============================================================================
# Notification method: ntfy, telegram, pushover, discord, or none
# =============================================================================
NOTIFY_METHOD=none

# --- Ntfy (recommended - free, self-hostable) ---
# NOTIFY_METHOD=ntfy
# NTFY_URL=https://ntfy.sh
# NTFY_TOPIC=my-random-topic-name
# NTFY_TOKEN=

# --- Telegram ---
# NOTIFY_METHOD=telegram
# TELEGRAM_BOT_TOKEN=
# TELEGRAM_CHAT_ID=

# --- Pushover ---
# NOTIFY_METHOD=pushover
# PUSHOVER_TOKEN=
# PUSHOVER_USER=

# --- Discord ---
# NOTIFY_METHOD=discord
# DISCORD_WEBHOOK_URL=

# =============================================================================
# Required settings
# =============================================================================

# External URL for approval links (your Tailscale/accessible URL)
GATE_URL=http://localhost:9999

# Your GitHub org/username
GITHUB_ORG=cameronsjo

# =============================================================================
# Optional settings
# =============================================================================

# GHCR authentication (for private images)
# Generate at: GitHub → Settings → Developer settings → Personal access tokens
# Scope: read:packages
GHCR_TOKEN=

# How often to check for updates (seconds)
POLL_INTERVAL=300

# Approval timeout (seconds) - how long before pending updates expire
APPROVAL_TIMEOUT=3600
"""

    env_file.write_text(env_content)
    print("✅ TOTP secret generated!")
    print()
    print(f"📁 Config saved to: {env_file}")
    print()
    print("=" * 60)
    print()

    show_qr(secret, issuer, account)

    print()
    print("=" * 60)
    print()
    print("Next steps:")
    print()
    print("1. Scan the QR code with your authenticator app")
    print("   (Google Authenticator, Authy, 1Password, etc.)")
    print()
    print(f"2. Edit {env_file} and add:")
    print("   - PUSHOVER_TOKEN and PUSHOVER_USER")
    print("   - GATE_URL (your Tailscale URL)")
    print()
    print("3. Create images.json with images to monitor:")
    print(f"   {config_dir / 'images.json'}")
    print()
    print("4. Start the service:")
    print("   docker-compose up -d")
    print()


def show_qr(secret: str, issuer: str, account: str):
    """Display QR code in terminal."""
    totp = pyotp.TOTP(secret)
    uri = totp.provisioning_uri(name=account, issuer_name=issuer)

    # Generate QR code
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=1,
        border=2,
    )
    qr.add_data(uri)
    qr.make(fit=True)

    print("📱 Scan this QR code with your authenticator app:")
    print()

    # Print QR code using Unicode blocks
    qr.print_ascii(invert=True)

    print()
    print(f"Or manually enter this secret: {secret}")
    print()
    print(f"Account: {account}")
    print(f"Issuer: {issuer}")


if __name__ == "__main__":
    main()
