# Strategy Two: TOTP Gate (Secure, Manual Approval)
#
# USE THIS FOR: Production apps, sensitive data, paranoid users
# SECURITY: If GitHub compromised, attacker blocked by TOTP on your phone.
#
# Add this file to your app repo at: .github/workflows/deploy.yml
# Then add entry to images.json on your Unraid approval gate.
#
# See: https://github.com/cameronsjo/not-that-terrible-at-all/blob/main/docs/choosing-a-strategy.md
#
# Security features enabled by default:
# - Cosign image signing (keyless via Sigstore)
# - SBOM attestation
# - Pinned actions (SHA, not version tags)
# - Config artifact sync (keeps docker-compose.yml in sync)
# - TOTP approval gate (requires 6-digit code from your phone)

name: Deploy to Unraid

on:
  push:
    branches:
      - main
      - master
  # Uncomment to also trigger on tags (for semver strategy)
  # tags:
  #   - 'v*'

  # Allow manual trigger from GitHub UI (works on phone!)
  workflow_dispatch:

jobs:
  deploy:
    # ┌─────────────────────────────────────────────────────────────┐
    # │ IMPORTANT: Update this to YOUR org/username                 │
    # │ This is the only line you need to change!                   │
    # └─────────────────────────────────────────────────────────────┘
    uses: cameronsjo/not-that-terrible-at-all/.github/workflows/deploy.yml@main

    # Inherit org-level secrets automatically
    secrets: inherit

    # Customize these inputs for your app
    with:
      # App name (used for image name in GHCR)
      # Defaults to repo name if not specified
      # app-name: my-cool-app

      # Path to Dockerfile (default: Dockerfile)
      # dockerfile: Dockerfile

      # Docker build context (default: .)
      # context: .

      # Target platforms (default: linux/amd64)
      # Add linux/arm64 for Raspberry Pi, Apple Silicon, etc.
      # platforms: linux/amd64,linux/arm64

      # Build arguments (one per line)
      # build-args: |
      #   NODE_ENV=production
      #   API_URL=https://api.example.com

      # Tagging strategy (default: latest)
      # Options: latest, sha, branch, semver
      # tag-strategy: latest

      # ┌─────────────────────────────────────────────────────────────┐
      # │ SECURITY OPTIONS                                            │
      # └─────────────────────────────────────────────────────────────┘

      # Sign images with cosign (default: true)
      # Enables Sigstore keyless signing + SBOM attestation
      sign-image: true

      # Push config artifact for TOTP gate to sync (default: true)
      # This keeps your docker-compose.yml in sync with your Git repo
      push-config: true

      # Config files to include in artifact (space-separated)
      # config-files: "docker-compose.yml config/nginx.conf"

      # Environment protection - requires approval before build
      # Set up the environment in GitHub repo settings first:
      #   Settings → Environments → New → "production" → Add yourself as reviewer
      # Then uncomment:
      # environment: production
